services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
  search_tool:
    build: ./flask_tools/serp
    
  weather_tool:
    build: ./flask_tools/openweather
   
    
  movie_tool:
    build: ./flask_tools/tmdb
    
  
  calendar_tool:
    build: ./flask_tools/calendar
    
  
  calculator_tool:
    build: ./flask_tools/calculator
   
    
  message_tool:
    build: ./flask_tools/message
    
  
  translator_tool:
    build: ./flask_tools/translator
   
  proxy_mgr:
    build: ./Toxiproxy
    volumes:
      - ./state:/app/state 
    depends_on:
      - toxiproxy

  agent:
    build: ./agent
    depends_on:
      toxiproxy: 
        condition: service_started
      search_tool: 
        condition: service_healthy
      weather_tool:
        condition: service_healthy
      movie_tool:
        condition: service_healthy
      calendar_tool:
        condition: service_healthy
      calculator_tool:
        condition: service_healthy
      message_tool:
        condition: service_healthy
      translator_tool:
        condition: service_healthy  
      proxy_mgr:
        condition: service_healthy
    volumes:
        - ./state:/app/state
        - ./logs:/app/logs
    environment:
      TOXIC_PROB: ${TOXIC_PROB}
      ERROR_PROB: ${ERROR_PROB}
      TOOL_LIMIT: ${TOOL_LIMIT}
      PROMPT_LIMIT: ${PROMPT_LIMIT}
    env_file:
      - .env
    

  

  
    


  
